-- let_err2 --
// redeclared in the same block (y has been declared in the top block)
y: 1
x: {
  let y = 2
  z: y
}
-- exp --
error: can not have both alias and field with name y in the same scope
